
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: test
        image: alpine
        resources: {}
        envFrom:
          - configMapRef:
             name: test